name: 'Build OpenSCAD file'
description: 'Build OpenSCAD files'
author: 'namachan10777'

inputs:
  input:
    description: '*.scad'
    required: true
    type: string
  output:
    description: 'output'
    type: string

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input }}
    - ${{ inputs.output }}
