# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
      - run: opam install dune ppx_inline_test odoc ocamlformat
      - run: opam exec -- dune runtest
      - run: opam exec -- dune build
      - run: opam exec -- dune build @fmt
      - run: opam exec -- dune build @doc