# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
      - run: opam install dune ppx_inline_test odoc ocamlformat

      - run: opam exec -- dune runtest

      - uses: ./actions/openscad
        with:
          input: _build/default/test/circle.scad
          output: circle.dxf
      - uses: ./actions/openscad
        with:
          input: _build/default/test/hello.scad
          output: hello.dxf
      - uses: ./actions/openscad
        with:
          input: _build/default/test/linear_extrude_circle.scad
          output: linear_extrude_circle.stl
      - uses: ./actions/openscad
        with:
          input: _build/default/test/mat_mul_cube.scad
          output: mat_mul_cube.stl
      - uses: ./actions/openscad
        with:
          input: _build/default/test/quat_cube.scad
          output: quat_cube.stl
      - uses: ./actions/openscad
        with:
          input: _build/default/test/quat_slerp.scad
          output: quat_slerp.stl
      - uses: ./actions/openscad
        with:
          input: _build/default/test/rotate_extrude_triangle.scad
          output: rotate_extrude_triangle.stl
      - uses: ./actions/openscad
        with:
          input: _build/default/test/square.scad
          output: square.dxf
      - uses: ./actions/openscad
        with:
          input: _build/default/test/triangle_polygon.scad
          output: triangle_polygon.dxf
      - uses: ./actions/openscad
        with:
          input: _build/default/test/vertical_text.scad
          output: vertical_text.dxf

      - run: opam exec -- dune build
      - run: opam exec -- dune build @fmt
      - run: opam exec -- dune build @doc
